### ISSUE TITLE
make menuconfig does not detect ncurses correctly

### ISSUE THREAD

**Issue by philipderrin** [seL4/seL4_tools#1]
`make menuconfig` will fail with an undefined symbol error if the system's ncurses was built with the `--with-termlib` option.

This was fixed in Linux in 3.10.rc1: torvalds/linux@fc9c6e000f62c2eeda426d4d5f022b3d57729bb0

**Comment by pingerino** [comment]
We're deprecating menuconfig very soon and shifting to a CMake based build system, so this won't get fixed.
