### ISSUE TITLE
ElfLoader CPU-ID display is incorrect

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4_tools#106]
The function `print_cpuid` decodes the CPUID_PART using the following logic:

```
    if ((CPUID_PART(cpuid) & 0xf00) == 0xC00) {
        printf("Cortex-A%d ", CPUID_PART(cpuid) & 0xff);
    } else if ((CPUID_PART(cpuid) & 0xf00) == 0xD00) {
        printf("Cortex-A5%d ", CPUID_PART(cpuid) & 0xff);
    } else {
        printf("Part: 0x%03x ", CPUID_PART(cpuid));
```

The logic is incorrect for at least the Cortex A35. It has a part id of 0xD04. The current logic incorrectly reports this as Cortex-A54.

I think the only robust approach is to explicitly list the part identifies. A potential implementation is:

```
    switch (CPUID_PART(cpuid)) {
        case 0xD04:
            printf("Cortex-A35 ");
            break;
        default:
            printf("Part: 0x%03x ", CPUID_PART(cpuid));
     }
```

This is a partial regression though as there are probably other Cortex parts that the current logic happens to print correctly.

Ideally there would be a full list. I only have a Cortex A35 to test on.

**Comment by axel-h** [comment]
Seems a duplicate of https://github.com/seL4/seL4_tools/issues/43 and as said there, please make a PR ;)

**Comment by bennoleslie** [comment]
Hah! Closing as it's an almost word for word dup.
