### ISSUE TITLE
RISC-V assembly startup code looks broken

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4_tools#114]
RISC-V assembly startup code at 
https://github.com/seL4/seL4_tools/blob/53d5db6b6f50652e11a6cb83915c6a8d9ca7d5d5/elfloader-tool/src/arch-riscv/crt0.S#L52
looks broken, I can't figure out why we use `x1` here. @wom-bat or @oliver-wm, could you clarify this? @yyshen any idea? This came in with https://github.com/seL4/seL4_tools/pull/68

**Comment by axel-h** [comment]
Why are we using `amoadd.w` and not just do something like this:
  ```
  .... // after ecall to probe for HSM extensions
  // Update global bool variable to tell boot code HSM extension exists.
  snez a0, a0  // a0 = (0 != a0) ? 1 : 0
  la t0, hsm_exists
  lw a0, 0(t0) // 32-bit store operation: [t0] = (int32)a0

  // Check if we are running on CONFIG_FIRST_HART_ID */
  li a1, CONFIG_FIRST_HART_ID
  beq  a1, s0, _start1  // if on FIRST_HART then -> _start1

  // If we are not on FIRST_HART, but the HSM extension is missing, there is 
  // nothing we can do to switch hards. Continue boot, maybe the C code can 
  // handle this case somehow, otherwise it should log a message and halt.
  beq  a0, x0, _start1
 
```

**Comment by yyshen** [comment]
> RISC-V assembly startup code at
> https://github.com/seL4/seL4_tools/blob/53d5db6b6f50652e11a6cb83915c6a8d9ca7d5d5/elfloader-tool/src/arch-riscv/crt0.S#L52
> 
> 
> looks broken, I can't figure out why we use `x1` here. @wom-bat or @oliver-wm, could you clarify this? @yyshen any idea? This came in with #68

That line should check if the HSM is supported. X1 contains 1 if it is supported.

**Comment by axel-h** [comment]
@yyshen: Are sue sure, which SBI does this? Please have a look at https://github.com/seL4/seL4_tools/pull/115, where I have a fixed version for OpenSBI. Specs say "... returns SBI_SUCCESS (0) in a0 if the call could be processed or an error code in not. On SBI_SUCCESS the value in a1 is 0 is the extension is not available or an extension-specific non-zero value if it is available."

**Comment by yyshen** [comment]
> @yyshen: Are sue sure, which SBI does this? Please have a look at #115, where I have a fixed version for OpenSBI. Specs say "... returns SBI_SUCCESS (0) in a0 if the call could be processed or an error code in not. On SBI_SUCCESS the value in a1 is 0 is the extension is not available or an extension-specific non-zero value if it is available."

If I am looking at the correct code [https://github.com/riscv-software-src/opensbi/blob/bd355213bfbb209c047e8cc0df56936f6705477f/lib/sbi/sbi_ecall_base.c#L18]

**Comment by axel-h** [comment]
but where does it write `x1`, this is just C code? And especially `x1` on RISC-V is the designated `ra` to store the return address and no function parameters.

**Comment by yyshen** [comment]
> but where does it write `x1`, this is just C code? And especially `x1` on RISC-V is the designated `ra` to store the return address and no function parameters.

Oops, I mixed up X1 in arm64 with the X1 in RISCV. X11 should be a1, as described in "SBI functions must return a pair of values in a0 and a1, with a0 returning an error code. This is analogous to returning the C structure".

**Comment by axel-h** [comment]
Could you check my fix proposal at https://github.com/seL4/seL4_tools/pull/115, then we can merge this.

**Comment by yyshen** [comment]
> Could you check my fix proposal at #115, then we can merge this.

try change   blt x1, s1, _start1 to blx a1,s1,_start1 to see if that can solve your issue.

**Comment by axel-h** [comment]
To play by the rules, we have to check `a0` first to ensure the SBI call itself was successful. Then we can check `a0` that holds the actual SBI function return code that the called.

**Comment by yyshen** [comment]
> To play by the rules, we have to check `a0` first to ensure the SBI call itself was successful. Then we can check `a0` that holds the actual SBI function return code that the called.

sure, should check a0 first to ensure it is 0. it is just the current sbi probe code for HSM always returns 0 in a0.

**Comment by axel-h** [comment]
yes, we should avoid making assumptions about the underlying SBI implementation beyond the API/ABI contract.

**Comment by yyshen** [comment]
> yes, we should avoid making assumptions about the underlying SBI implementation beyond the API/ABI contract.

let us see if changing x1 to a1 corrects the issue first, to see if it is the root cause?

**Comment by kent-mcleod** [comment]
> let us see if changing x1 to a1 corrects the issue first, to see if it is the root cause?

Thanks for putting up the fix @axel-h. Are you able to split https://github.com/seL4/seL4_tools/pull/115 apart so that it just has changes necessary to address this issue? Other rewriting work that is unrelated to this issue means it takes longer to review.

**Comment by yyshen** [comment]
> > let us see if changing x1 to a1 corrects the issue first, to see if it is the root cause?
> 
> Thanks for putting up the fix @axel-h. Are you able to split #115 apart so that it just has changes necessary to address this issue? Other rewriting work that is unrelated to this issue means it takes longer to review.

Agree with that. if possible, bug PRs should be separated from improvement, new feature, or styling PRs. Reviewers appreciate a sequence of easy-to-understand concise PRs. Thanks.

**Comment by axel-h** [comment]
I've already tried to split up the commits. The one commit https://github.com/seL4/seL4_tools/pull/115/commits/d6e87c2710cf228f84ee0187512ffc065e287c97 now uses the HSM extension properly with and checks the return code(s) correctly.

**Comment by kent-mcleod** [comment]
> I've already tried to split up the commits. The one commit [d6e87c2](https://github.com/seL4/seL4_tools/commit/d6e87c2710cf228f84ee0187512ffc065e287c97) now uses the HSM extension properly with and checks the return code(s) correctly.

This commit is changing more than just x1 to a1 and checking a0 is 0.  I'd expect these changes to only need 3 or 4 lines of assembly around https://github.com/seL4/seL4_tools/commit/d6e87c2710cf228f84ee0187512ffc065e287c97#diff-faea38921f2a3c37a8a44d1709d1f61596d8ee0f61e8071a103d6203fa713981L74 to check a0 and a1 are valid and jumping to _start1 if not.  

The rest of the commit looks to be rewriting the control flow of the file and making other changes.  Why do these need to be part of the same commit?
