### ISSUE TITLE
macOS shell touch binary implement not support "@0" alias

### ISSUE THREAD

**Issue by HHPLow** [seL4/seL4_tools#119]
Hi:
When I use macOS to build the seL4 project, will meet an error about `touch`

```
touch: out of range or illegal time specification: YYYY-MM-DDThh:mm:SS[.frac][tz]
[251/263] Building C object kernel/CMakeFiles/kernel.elf.dir/kernel_all.c.obj
```

issue command is 
```shell
 touch -d @0 `basename ${file}`
```
https://github.com/seL4/seL4_tools/blob/6211394b3f83eed47a2abe80b81af608846cdb66/cmake-tool/helpers/cpio.cmake#L51

information of "@0"
https://unix.stackexchange.com/questions/154387/meaning-of-0-in-a-shell-script

macOS touch help
```
   -d      Change the access and modification times to the specified date time instead of the current time of day.  The argument is of the form
             “YYYY-MM-DDThh:mm:SS[.frac][tz]” where the letters represent the following:
                   YYYY    At least four decimal digits representing the year.
                   MM, DD, hh, mm, SS
                           As with -t time.
                   T       The letter T or a space is the time designator.
                   .frac   An optional fraction, consisting of a period or a comma followed by one or more digits.  The number of significant digits depends on
                           the kernel configuration and the filesystem, and may be zero.
                   tz      An optional letter Z indicating the time is in UTC.  Otherwise, the time is assumed to be in local time.  Local time is affected by
                           the value of the TZ environment variable.
```

There have some differences with GNU touch, so this command will error on macOS.

Thanks~

**Comment by lsf37** [comment]
Hi @HHPLow: building on macOS is not supported, the tool chain assumes a GNU environment (there'll be many more places where things break, even simple things like `stat` already).

If you're developing on a Mac, I'd recommend using the [docker images][0] or a Linux VM for the tool chain invocations (while editing natively on the Mac). At least that's the setup I'm using myself.

[0]: https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles

**Comment by HHPLow** [comment]
Got it
Thanks, @lsf37
