### ISSUE TITLE
Setting `UseRiscVOpenSBI` has no affect

### ISSUE THREAD

**Issue by Ivan-Velickovic** [seL4/seL4_tools#164]
For example, running the following with seL4test:

`../init-build.sh -DPLATFORM=hifive -DUseRiscVOpenSBI=OFF` still produces an image with OpenSBI. The option is defined in `rootserver.cmake` with `cmake_dependent_option`. The CMake documentation (https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html) says that the option should be available to the user, although I don't know what their definition of user is.

**Comment by axel-h** [comment]
Readinf thge docs, I wonder if the line
```
cmake_dependent_option(UseRiscVOpenSBI "Use OpenSBI." ON DEPENDS "KernelArchRiscV" OFF)
```
should actually be
```
cmake_dependent_option(UseRiscVOpenSBI "Use OpenSBI." ON "KernelArchRiscV" OFF)
```

**Comment by Ivan-Velickovic** [comment]
Ah I missed that, that worked. Thanks! I will make a PR.
