### ISSUE TITLE
Cannot generate opensbi/platform/generic/firmware/fw_payload.elf

### ISSUE THREAD

**Issue by tkf2019** [seL4/seL4_tools#169]
I'm trying to run sel4test on plat `qemu-riscv-virt` with commands:

```sh
mkdir build-riscv
cd build-riscv
../init-build.sh -DRISCV64=1 -DSIMULATION=TRUE -DPLATFORM=qemu-riscv-virt
ninja
```

The log shows the error:

```
Error: unrecognized opcode `fence.i', extension `zifencei' required
```

I find that the command generated in build.ninja builds opensbi with `PLATFORM_RISCV_ISA=rv64imafdc PLATFORM_RISCV_ABI=lp64d`. This env is generated by [this line](https://github.com/seL4/seL4_tools/blob/2c61d6a0b561b8d4a6904494df5118a2545bf143/cmake-tool/helpers/rootserver.cmake#L113):

```
if(NOT OPENSBI_PLAT_ISA)
    set(OPENSBI_PLAT_ISA "rv${OPENSBI_PLAT_XLEN}imafdc")
endif()
```

 Should it be `set(OPENSBI_PLAT_ISA "rv${OPENSBI_PLAT_XLEN}imafdc_zifencei")` instead?

**Comment by Ivan-Velickovic** [comment]
I believe I’ve seen this behaviour depending on the compiler used, could you list the compiler triple used and the version?

**Comment by tkf2019** [comment]
I find that changing the command can solve this problem:

```
mkdir build-riscv
cd build-riscv
../init-build.sh -DRISCV64=1 -DSIMULATION=TRUE -DPLATFORM=qemu-riscv-virt -DOPENSBI_PLAT_ISA=rv64imafdc_zifencei
ninja
```

The compiler triple used and the version:

```
riscv64-unknown-linux-gnu-g++ (g2ee5e430018) 12.2.0
```

**Comment by Ivan-Velickovic** [comment]
Yes, I believe newer toolchains (GCC 12+, maybe even GCC 11) do not enable the `Zifencei` extension and possibly others such as `Zicsr` by default. I believe CMake has a way of getting the compiler version so we can set `OPENSBI_PLAT_ISA` depending on the compiler version so we do not break older toolchains.

**Comment by axel-h** [comment]
Looks like https://github.com/seL4/seL4/pull/776 and what we do in https://github.com/seL4/seL4/blob/2730e6579677174d4fbe517c1aec9c22b7638067/CMakeLists.txt#L128:L139 now.

**Comment by Ivan-Velickovic** [comment]
I believe this is fixed in https://github.com/seL4/seL4_tools/commit/a9d1b6d2b127830d6205e46c983d63e5bb561449 now. Let us know if you still have an issue with compiling for RISC-V. Thanks for reporting the issue.
