### ISSUE TITLE
print_cpuid display incorrect data for at least Cortex-A35

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4_tools#43]
The function `print_cpuid` incorrectly calculates the CPU name associated with the part number.

The current code is:

```
    if ((CPUID_PART(cpuid) & 0xf00) == 0xC00) {
        printf("Cortex-A%d ", CPUID_PART(cpuid) & 0xff);
    } else if ((CPUID_PART(cpuid) & 0xf00) == 0xD00) {
        printf("Cortex-A5%d ", CPUID_PART(cpuid) & 0xff);
    } else {
        printf("Part: 0x%03x ", CPUID_PART(cpuid));
```

However, the Cortex-A35 `part` is `0xD04`. The current logic prints that as `Cortex-A54`, which is obviously wrong.

I think the assumptions made in this printing is just incorrect. A switch-based look up table is probably most appropriate. Something like:

```
    switch (CPUID_PART(cpuid)) {
       case 0xD04:
           printf("Cortex-A35 ");
            break;
        default:
            printf("Part: 0x%03x ", CPUID_PART(cpuid));
     }
```

But, obviously, with additional switch statements for other, supported, CPUs.

**Comment by axel-h** [comment]
Sounds reasonable to me. Can you make a pull request with a patch?

**Comment by bennoleslie** [comment]
OK. I finally made a pull request: https://github.com/seL4/seL4_tools/pull/107
