### ISSUE TITLE
ElfLoader should use monitor.S only if CONFIG_ARM_MONITOR_HOOK is set

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4_tools#47]
The file monitor.S should only be compiled in (or it's content take into account), when CONFIG_ARM_MONITOR_HOOK is set. Otherwise the content should be ignored, so any accidental referenced make the build fail. 

We ran into this issue when adding a new imx6 board platform, where we had to define something there to VECTOR_BASE even if this is not used anywhere because CONFIG_ARM_MONITOR_HOOK is not supported there.

**Comment by axel-h** [comment]
See also https://github.com/seL4/seL4_tools/pull/53

**Comment by kent-mcleod** [comment]
Resolved by https://github.com/seL4/seL4_tools/pull/56
