### ISSUE TITLE
delete merged and stale branches

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4_tools#55]
While I'm on it, here are a few more branches that look obsolete:
- already merged
  - `gklein/github-ci` 
  - `kent/fpu`
- potentially stale branches to be considered for deletion
  - `lsf37-patch-1`
  - `nomadeel/use-kernel-dtb`
  - `alyons-pr`

**Comment by lsf37** [comment]
Done. Same issue as in other repo. Thanks for pointing these out.

**Comment by axel-h** [comment]
@kent-mcleod : There is also `tipc-stage`, is this still something to keep?

**Comment by kent-mcleod** [comment]
> @kent-mcleod : There is also `tipc-stage`, is this still something to keep?

@ikuz this was from an intermediate project milestone.  Is it able to be deleted now?
