### ISSUE TITLE
elfloader, Arm: Issues with clearing .bss and stack regions during early init

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/seL4_tools#65]
The elfloader calls `clear_bss` early in its init process to zero the `.bss` section under some configurations to handle situations where the loader didn't zero any uninitialized memory.  Because the elfloader's stack is declared in the .bss section this means that with correct operation of `clear_bss` the stack would be cleared in the middle.  Consequences of this are crashing under high optimization levels (because under low optimization the stack doesn't get used in `clear_bss`) and erasing an arguments provided to the elfloader by an earlier stage that are stored on the stack.

This would have been detected much earlier if not for a separate issue involving the linker script:
```
    .bss : {
        _bss = .;
        *(.bss)
        _bss_end = .;
    }
```
This script means that zeroing from _bss to _bss_end will zero any symbol that had been matched by `*(.bss)`.  Before gcc-10, any global variables that are declared but uninitialized would be instead placed in the `COMMON` section until the final link stage. Because the linker script above is missing `*(COMMON)`, any of these symbols would end up after _bss_end.  This includes the stack and essentially every other global variable that would be in .bss in the elfloader.  

With gcc-10 changing to default -fno-common, these variables stop being excluded from `clear_bss` however this means that now the stack gets zeroed while the stack is being used.

Fixing this should resolve a few stability issues found when using configurations that call `clear_bss`:
- CONFIG_IMAGE_BINARY on aarch64
- CONFIG_IMAGE_ELF, CONFIG_IMAGE_BINARY, CONFIG_IMAGE_UIMAGE on aarch32

**Comment by oliver-wm** [comment]
Nice!
