### ISSUE TITLE
asm code calls clear_bss without a valid stack pointer

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4_tools#84]
In https://github.com/seL4/seL4_tools/pull/82 we call `clear_bss` from asm code now when `CONFIG_IMAGE_BINARY` is enabled - but there is no stack set up. This is a bit dangerous, since C code always assumes there is stack. It may work if the function is simple enough so C does not create a stack frame.

**Comment by axel-h** [comment]
This will be fixed when https://github.com/seL4/seL4_tools/pull/135 is merged, as a proper stack pointer is set up then.

**Comment by kent-mcleod** [comment]
Fixed by https://github.com/seL4/seL4_tools/pull/136
